[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "GitHub"
  url = "https://github.com/smerck/blog"
  weight = 40


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
